name: E2E Tests
on: [push]

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test

      - name: Start Application
        run: npm start

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6.5.0
        with:
          start: npm start
          wait-on: "http://localhost:3000"
